//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Respondent.Respository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public System.Guid PhoneId { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid PersonId { get; set; }
        public string PhoneTypeCode { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
